void arcana_water_son_1() {
  anum = random(0, 7);
  jnum = random(0, 2);
  jjnum = random(0, 3);
  
  PAUSE_POINT();
  for (int i = 0; i < 2; i++) {
  PAUSE_POINT();
  Jumpdivideleft();
  PAUSE_POINT();
  Jumpdivide4(); 
  PAUSE_POINT();
  pUp();
  PAUSE_POINT();
  pressTwoKey_50('d', 'f');
  PAUSE_POINT();
  rF();
  PAUSE_POINT();
  d_val(550);
  PAUSE_POINT();
  Jumpdivideright();
  PAUSE_POINT();
  Jumpdivide();
  PAUSE_POINT();
  Jumpdivide3();
  PAUSE_POINT();
  Rjump();
  PAUSE_POINT();
  Q();
  PAUSE_POINT();
  d_val(610);
  PAUSE_POINT();
  }
  PAUSE_POINT();

  PAUSE_POINT();
  for (int i = 0; i < 1; i++) {
  PAUSE_POINT();
  Jumpdivideleft();
  PAUSE_POINT();
  Jumpdivide4(); 
  PAUSE_POINT();
  pUp();
  PAUSE_POINT();
  pressTwoKey_50('d', 'f');
  PAUSE_POINT();
  rF();
  PAUSE_POINT();
  d_val(550);
  PAUSE_POINT();
  Jumpdivideright();
  PAUSE_POINT();
  Jumpdivide();
  PAUSE_POINT();
  S10();
  d_Main();
  PAUSE_POINT();
  Jumpdivide3();
  PAUSE_POINT();
  Rjump();
  PAUSE_POINT();
  Q();
  PAUSE_POINT();
  d_val(600);
  PAUSE_POINT();

  PAUSE_POINT();
  Jumpdivideleft();
  PAUSE_POINT();
  Jumpdivide4(); 
  PAUSE_POINT();
  pUp();
  PAUSE_POINT();
  pressTwoKey_50('d', 'f');
  PAUSE_POINT();
  rF();
  PAUSE_POINT();
  d_val(570);
  PAUSE_POINT();
  Jumpdivideright();
  PAUSE_POINT();
  Jumpdivide();
  PAUSE_POINT();
  S1();
  PAUSE_POINT();
  Jumpdivide3();
  PAUSE_POINT();
  Rjump();
  PAUSE_POINT();
  Q();
  PAUSE_POINT();
  d_val(610);  
  PAUSE_POINT();
  }
  PAUSE_POINT();

  PAUSE_POINT();
  Jumpdivideleft();
  PAUSE_POINT();
  Jumpdivide();
  PAUSE_POINT();
  S6();
  PAUSE_POINT();
  Jumpdivide3(); 
  PAUSE_POINT();
  pUp();
  PAUSE_POINT();
  pressTwoKey_50('d', 'f');
  PAUSE_POINT();
  rF();
  PAUSE_POINT();
  d_val(560);
  PAUSE_POINT();
  Jumpdivideright();
  PAUSE_POINT();
  Jumpdivide4();
  PAUSE_POINT();
  Rjump();
  PAUSE_POINT();
  Q();
  PAUSE_POINT();
  d_val(620);
  PAUSE_POINT();

  PAUSE_POINT();
  for (int i = 0; i < 3; i++) {
  PAUSE_POINT();
  Jumpdivideleft();
  PAUSE_POINT();
  Jumpdivide4(); 
  PAUSE_POINT();
  pUp();
  PAUSE_POINT();
  pressTwoKey_50('d', 'f');
  PAUSE_POINT();
  rF();
  PAUSE_POINT();
  d_val(580);
  PAUSE_POINT();
  Jumpdivideright();
  PAUSE_POINT();
  Jumpdivide();
  PAUSE_POINT();
  S10();
  d_Main();
  PAUSE_POINT();
  Jumpdivide3();
  PAUSE_POINT();
  Rjump();
  PAUSE_POINT();
  Q();
  PAUSE_POINT();
  d_val(600);
  PAUSE_POINT();

  PAUSE_POINT();
  Jumpdivideleft();
  PAUSE_POINT();
  Jumpdivide4(); 
  PAUSE_POINT();
  pUp();
  PAUSE_POINT();
  pressTwoKey_50('d', 'f');
  PAUSE_POINT();
  rF();
  PAUSE_POINT();
  d_val(560);
  PAUSE_POINT();
  Jumpdivideright();
  PAUSE_POINT();
  Jumpdivide();
  PAUSE_POINT();
  S1();
  PAUSE_POINT();
  Jumpdivide3();
  PAUSE_POINT();
  Rjump();
  PAUSE_POINT();
  Q();
  PAUSE_POINT();
  d_val(600);  
  PAUSE_POINT();
  }
  PAUSE_POINT();

  PAUSE_POINT();
  Jumpdivideleft();
  PAUSE_POINT();
  Jumpdivide();
  PAUSE_POINT();
  S11();
  PAUSE_POINT();
  Jumpdivide3(); 
  PAUSE_POINT();
  pUp();
  PAUSE_POINT();
  pressTwoKey_50('d', 'f');
  PAUSE_POINT();
  rF();
  PAUSE_POINT();
  d_val(550);
  PAUSE_POINT();
  Jumpdivideright();
  PAUSE_POINT();
  Jumpdivide4();
  PAUSE_POINT();
  Rjump();
  PAUSE_POINT();
  Q();
  PAUSE_POINT();
  d_val(600);
  PAUSE_POINT();
  
  Reset();
}
